"""
Stage 2: LLM Re-ranker.
Takes Stage 1 candidates + user context and uses Claude to re-prioritise.
"""

import json
import re
import os
from typing import List, Optional
import httpx


RERANKER_SYSTEM_PROMPT = """You are an expert recommendation re-ranker for a movie/product recommendation system.

You will receive:
1. A list of candidate items generated by a collaborative filtering model
2. A user's rating history (what they liked/disliked)
3. Optional user context (mood, occasion, stated preferences)

Your task is to RE-RANK the candidates by considering:
- The user's taste profile inferred from their history
- Their current context/mood if provided
- Diversity of recommendations (avoid all items being from one genre)
- Recency/novelty balance

IMPORTANT: You must respond ONLY with a valid JSON object in this exact format:
{
  "ranked_items": [
    {
      "item_id": "...",
      "rank": 1,
      "score": 0.95,
      "reason": "Short 1-sentence explanation"
    }
  ],
  "rerank_summary": "Brief 2-sentence summary of your re-ranking strategy"
}

Scoring rubric:
- Use the provided signals (cf_score, popularity, freshness, similarity_to_likes) to inform ranking, but you may override based on context.
- Prefer diversity: avoid placing too many items of the same genre in the top results unless the user context strongly demands it.

Do not include any text outside the JSON. Include ALL items from the input, just re-ordered."""


async def llm_rerank(
    candidates: List[dict],
    user_history: List[dict],
    user_context: Optional[str] = None,
    top_k: int = 10,
    api_key: Optional[str] = None,
) -> dict:
    """
    Re-rank candidates using Claude.
    
    Args:
        candidates: Stage 1 output — list of candidate items
        user_history: User's rated items with ratings
        user_context: Optional free-text context ("I want something light tonight")
        top_k: How many final results to return
    
    Returns:
        dict with "ranked_items" and "rerank_summary"
    """

    # Build user prompt
    user_prompt = _build_rerank_prompt(candidates, user_history, user_context)

    resolved_key = (api_key or "").strip() or os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not resolved_key:
        # No Anthropic key: run a deterministic local fallback reranker.
        return _fallback_rerank(candidates, user_history, user_context, top_k)

    # Call Claude API
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "Content-Type": "application/json",
                "anthropic-version": "2023-06-01",
                "x-api-key": resolved_key,
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 2000,
                "system": RERANKER_SYSTEM_PROMPT,
                "messages": [{"role": "user", "content": user_prompt}],
            },
        )

    if response.status_code != 200:
        raise RuntimeError(f"Claude API error {response.status_code}: {response.text}")

    raw = response.json()
    text = raw["content"][0]["text"]

    # Parse JSON response
    result = _parse_llm_response(text)

    # Merge back full metadata
    item_lookup = {c["item_id"]: c for c in candidates}
    for item in result["ranked_items"]:
        meta = item_lookup.get(item["item_id"], {})
        item.update({k: v for k, v in meta.items() if k not in item})

    # Guardrails: diversity cap before trimming
    result["ranked_items"] = _enforce_diversity(result.get("ranked_items", []), max_per_genre=3)
    # Re-number ranks after any re-ordering.
    for i, it in enumerate(result["ranked_items"], start=1):
        it["rank"] = i

    # Trim to top_k
    result["ranked_items"] = result["ranked_items"][:top_k]

    return result


def _build_rerank_prompt(
    candidates: List[dict],
    user_history: List[dict],
    user_context: Optional[str],
) -> str:
    # Summarise history (top 10 by rating)
    history_summary = []
    for h in user_history[:10]:
        history_summary.append(
            f"- {h.get('title', h['item_id'])} "
            f"({h.get('genre', 'unknown genre')}) — rated {h['rating']}/5"
        )

    def _popularity_signal(item_id: str) -> float:
        # Candidate may include a precomputed popularity; otherwise default.
        for c in candidates:
            if c.get("item_id") == item_id and c.get("popularity") is not None:
                try:
                    return float(c["popularity"])
                except Exception:
                    return 0.0
        return 0.0

    def _freshness_signal(c: dict) -> float:
        # Normalise year to 0..1 if present; otherwise 0.5.
        year = c.get("year")
        if not year:
            return 0.5
        try:
            y = int(year)
        except Exception:
            return 0.5
        # These datasets are tiny; clamp between 1970..2026.
        lo, hi = 1970, 2026
        return max(0.0, min(1.0, (max(lo, min(hi, y)) - lo) / (hi - lo)))

    def _similarity_to_likes(c: dict) -> float:
        # Lightweight similarity: genre match + tag overlap with top liked items.
        liked = [h for h in user_history if h.get("rating", 0) >= 4.0][:8]
        if not liked:
            return 0.0
        c_genre = (c.get("genre") or "").lower()
        c_tags = set([t.lower() for t in (c.get("tags") or [])])
        score = 0.0
        for h in liked:
            if (h.get("genre") or "").lower() == c_genre and c_genre:
                score += 0.6
            h_tags = set([t.lower() for t in (h.get("tags") or [])])
            if c_tags and h_tags:
                score += 0.4 * (len(c_tags & h_tags) / max(1, len(c_tags | h_tags)))
        return min(1.0, score / max(1, len(liked)))

    # Format candidates (pass predicted rating + extra signals)
    candidate_list = []
    for c in candidates:
        sim = _similarity_to_likes(c)
        fresh = _freshness_signal(c)
        popularity = c.get("popularity")
        try:
            popularity = float(popularity) if popularity is not None else 0.0
        except Exception:
            popularity = 0.0

        candidate_list.append({
            "item_id": c["item_id"],
            "title": c.get("title", c["item_id"]),
            "genre": c.get("genre", "unknown"),
            "year": c.get("year", ""),
            "cf_score": round(c.get("predicted_rating", 3.0), 3),
            "tags": c.get("tags", []),
            "popularity": round(popularity, 3),
            "freshness": round(fresh, 3),
            "similarity_to_likes": round(sim, 3),
        })

    prompt = f"""CANDIDATE ITEMS (from collaborative filtering, {len(candidates)} total):
{json.dumps(candidate_list, indent=2)}

USER RATING HISTORY (most recent/highest rated first):
{chr(10).join(history_summary) if history_summary else "No history available (cold-start user)"}

USER CONTEXT / MOOD:
{user_context if user_context else "Not specified"}

Please re-rank all {len(candidates)} candidates and return the JSON."""

    return prompt


def _enforce_diversity(ranked_items: List[dict], max_per_genre: int = 3) -> List[dict]:
    # Simple guardrail: cap genre frequency in the ordered list.
    out = []
    counts = {}
    leftovers = []
    for it in ranked_items:
        g = (it.get("genre") or "unknown").lower()
        if counts.get(g, 0) < max_per_genre:
            out.append(it)
            counts[g] = counts.get(g, 0) + 1
        else:
            leftovers.append(it)
    return out + leftovers


def _fallback_rerank(
    candidates: List[dict],
    user_history: List[dict],
    user_context: Optional[str],
    top_k: int,
) -> dict:
    """
    Local reranker used when ANTHROPIC_API_KEY is not configured.
    """
    liked = [h for h in user_history if float(h.get("rating", 0)) >= 4.0]
    liked_genres = [str(h.get("genre", "")).lower() for h in liked if h.get("genre")]
    genre_counts = {}
    for g in liked_genres:
        genre_counts[g] = genre_counts.get(g, 0) + 1
    top_genres = set(sorted(genre_counts, key=lambda g: -genre_counts[g])[:2])

    def _context_bonus(item: dict) -> float:
        if not user_context:
            return 0.0
        ctx = user_context.lower()
        text = " ".join(
            [
                str(item.get("title", "")),
                str(item.get("genre", "")),
                " ".join(item.get("tags", []) or []),
            ]
        ).lower()
        hits = sum(1 for token in ctx.split() if len(token) > 3 and token in text)
        return min(0.25, hits * 0.05)

    scored = []
    for c in candidates:
        cf = float(c.get("predicted_rating", 3.0)) / 5.0
        pop = float(c.get("popularity", 0.0))
        fresh = 0.5
        if c.get("year"):
            try:
                y = int(c["year"])
                fresh = max(0.0, min(1.0, (max(1970, min(2026, y)) - 1970) / (2026 - 1970)))
            except Exception:
                fresh = 0.5
        genre = str(c.get("genre", "")).lower()
        pref = 1.0 if genre in top_genres else 0.0
        ctx = _context_bonus(c)

        score = 0.6 * cf + 0.15 * pop + 0.1 * fresh + 0.1 * pref + 0.05 * ctx
        scored.append((score, c))

    sorted_scored = sorted(scored, key=lambda x: -x[0])
    score_map = {c.get("item_id"): s for s, c in sorted_scored}
    ranked = [c for _, c in sorted_scored]
    ranked = _enforce_diversity(ranked, max_per_genre=3)

    ranked_items = []
    for i, item in enumerate(ranked[:top_k], start=1):
        ranked_items.append(
            {
                **item,
                "rank": i,
                "score": round(max(0.01, min(0.99, float(score_map.get(item.get("item_id"), 0.5)))), 3),
                "reason": "Ranked by local signals (CF score, preferences, freshness, and diversity).",
            }
        )

    return {
        "ranked_items": ranked_items,
        "rerank_summary": "Using local fallback reranker (no Anthropic key). "
        "Add ANTHROPIC_API_KEY any time to enable Claude-based re-ranking.",
    }


def _parse_llm_response(text: str) -> dict:
    """Robustly parse JSON from LLM output."""
    # Strip markdown fences if present
    text = re.sub(r"```json\s*", "", text)
    text = re.sub(r"```\s*", "", text)
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Try to extract JSON object from text
        match = re.search(r"\{[\s\S]+\}", text)
        if match:
            return json.loads(match.group())
        raise ValueError(f"Could not parse LLM response as JSON:\n{text[:500]}")
